# Generated by Django 3.1.3 on 2021-04-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cspe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='horsepower',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='mileage',
            field=models.FloatField(),
        ),
    ]
